# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 BuildWorks.AI
apiVersion: v1
kind: Service
metadata:
  name: eucora-api
  namespace: eucora
  labels:
    app: eucora-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: eucora-api
