# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 BuildWorks.AI
apiVersion: v1
kind: ConfigMap
metadata:
  name: eucora-config
  namespace: eucora
data:
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_USE_SSL: "false"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  CELERY_TIMEZONE: "UTC"
  CELERY_ENABLE_UTC: "true"
